### ISSUE TITLE
请问哪里还能找到关于 github battle 的视频教程

### ISSUE THREAD

**Issue by hacker0limbo** [qwas3110/React-GitHub-Battle#1]
前辈您好, 打扰了, 请问哪里还能搜到相关 github battle 的视频教程? 这个教程有些老了, 所以网上搜到的都只有代码, 想请问前辈是否能分享 一下哪里可以找到相关视频资源? 打扰了, 谢谢

**Comment by qwas3110** [comment]
https://learn.tylermcginnis.com/

**Comment by hacker0limbo** [comment]
> https://learn.tylermcginnis.com/

好的, 多谢!
